config/routes.rb
Rails.application.routes.draw do
  resources :livros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "livros#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/livro.rb
class Livro < ApplicationRecord
  validates :titulo, :autor, :nota, :descricao, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy!

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :nota, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteRailsDio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> este livro não pode ser salvo:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <div>
      <%= form.label :titulo, class: "form-label" %>
      <%= form.text_field :titulo, class: "form-control border-primary" %>
    </div>
  </div>

  <div class="mb-3">
    <div>
      <%= form.label :autor, class: "form-label" %>
      <%= form.text_field :autor, class: "form-control border-primary" %>
    </div>
  </div>

  <div class="mb-3">
    <div>
      <%= form.label :nota, class: "form-label" %>
      <%= form.number_field :nota, class: "form-control border-primary" %>
    </div>
  </div>

  <div class="mb-3">
    <div>
      <%= form.label :descricao, class: "form-label" %>
      <%= form.text_area :descricao, class: "form-control border-primary" %>
    </div>
  </div>
  <div class="row gy-3">
  <div class="col-md-2">
    <%= form.submit class: "btn btn-primary", value: "Criar" %>
  </div>
<% end %>

app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>">
  <h1>
    <strong>Titulo:</strong>
    <%= livro.titulo %>
  </h1>

  <p>
    <strong>Autor:</strong>
    <%= livro.autor %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= livro.nota %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= livro.descricao %>
  </p>

</div>

app/views/livros/edit.html.erb
<div class="container">
  <h1>Editar livro</h1>
  <%= render "form", livro: @livro %>

    <div>
      <div class="row gy-3">
        <div class="col-md-2">
          <%= link_to "Ver este livro" , @livro, class: "btn btn-primary" %>
        </div>
        <div class="col-md-2">
          <%= link_to "Voltar para livros" , livros_path, class: "btn btn-primary" %>
        </div>
      </div>

    </div>
</div>

app/views/livros/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">

    <h1>Livros</h1>

    <%= link_to "Novo livro", new_livro_path, class: "btn btn-primary" %>
    <hr class="my-6">

    <div id="livros">
      <% @livros.each do |livro| %>
        <%= render livro %>
        <p>
          <%= link_to "Abrir este livro", livro, class: "btn btn-primary" %>
        </p>
        <hr class="my-4">
      <% end %>

</div>


</div>

app/views/livros/new.html.erb
<div class="container">
<h1>New livro</h1>

<%= render "form", livro: @livro %>

<br>

<div class="col-md-2">
  <%= link_to "Voltar para livros", livros_path, class: "btn btn-primary" %>
</div>

</div>
</div>

app/views/livros/show.html.erb
<p style="color: green">
  <%= notice %>
</p>
<div class="container">
  <%= render @livro %>

    <div>
      <div class="row gy-3">
        <div class="col-md-2">
          <%= link_to "Editar este livro" , edit_livro_path(@livro), class: "btn btn-primary" %>
        </div>
        <div class="col-md-2">
          <%= link_to "Voltar para livros" , livros_path, class: "btn btn-primary" %>
        </div>
        <div class="col-md-2">
          <%= button_to "Destruir este livro" , @livro, method: :delete, class: "btn btn-danger" %>
        </div>
      </div>

    </div>
</div>